### ISSUE TITLE
Stylus failed to parse usercss

### ISSUE THREAD

**Issue by CodeIter** [goatgitt/scrollbar_mullticolor#2]
Hello, i get this error message
```
Stylus failed to parse usercss:
Could not find metadata.
```
**Brave Browser** `Version 1.35.103` _Chromium_: `98.0.4758.102` (`Official Build`) (**64-bit**)
**Stylus extension** `Version 1.5.22`

**Comment by goatgitt** [comment]
Hello,
Did you try to copy and paste the file css into stylus?
best,

**Comment by CodeIter** [comment]
Hi, this because:
Userscript metadata start with `/* ==UserStyle==` and end with `==/UserStyle== */`
https://github.com/goatgitt/Progressbar_mullticolor/blob/a53f7ccacee0f11a561853fea7f19685e172eac6/Progressbar_multicolor.css#L11
